# -*- coding: utf-8 -*-
"""curriculum_service.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dXc9i2iTkFMad7bf4UlCjL-9Pzax49yR
"""

from google.colab import drive
drive.mount('/content/drive')

from typing import Dict
from evaluation_service import EvaluationService

class CurriculumManager:
    """
    Decides when to advance to the next tier based on competence metrics.
    """
    def __init__(
        self,
        max_tiers: int = 5,
        accuracy_threshold: float = 0.85,
        loss_stability_threshold: float = 1e-3,
        window_size: int = 5
    ):
        self.max_tiers = max_tiers
        self.current_tier = 1
        self.accuracy_threshold = accuracy_threshold
        self.loss_stability_threshold = loss_stability_threshold
        self.window_size = window_size
        self.is_completed = False

    def should_advance(self, evaluation_service: EvaluationService) -> bool:
        """
        Determines if the model should advance to the next tier.
        Rule: Moving Avg Acc >= Threshold AND Loss is Stable.
        """
        if self.current_tier >= self.max_tiers:
            self.is_completed = True
            return False

        avg_acc = evaluation_service.get_moving_average_accuracy(self.window_size)
        stable = evaluation_service.is_loss_stable(self.loss_stability_threshold, self.window_size)

        print(f"Tier {self.current_tier} Status: MovingAvg Accuracy={avg_acc:.4f} (Threshold: {self.accuracy_threshold}), Loss Stable={stable}")

        if avg_acc >= self.accuracy_threshold and stable:
            return True
        return False

    def advance_tier(self):
        if self.current_tier < self.max_tiers:
            self.current_tier += 1
            print(f"*** PROMOTION! Advancing to Tier {self.current_tier} ***")
        else:
            self.is_completed = True
            print("*** Curriculum Completed! ***")

    def get_config_state(self) -> Dict:
        """Returns state for checkpointing."""
        return {
            'current_tier': self.current_tier,
            'is_completed': self.is_completed
        }

    def load_config_state(self, state: Dict):
        """Restores state from checkpoint."""
        self.current_tier = state.get('current_tier', 1)
        self.is_completed = state.get('is_completed', False)