# -*- coding: utf-8 -*-
"""base_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjI_7Vgh4Gmr40chNR2_srtD4-jyRXAl
"""

from abc import ABC, abstractmethod
from typing import Dict, Any
import torch

class ModelAdapter(ABC):
    """
    Abstract Interface for VQA models.
    """

    @abstractmethod
    def train_step(self, batch: Dict[str, Any]) -> Dict[str, float]:
        """
        Performs a single training step.
        Returns dictionary of metrics (e.g., {'loss': 2.3})
        """
        pass

    @abstractmethod
    def validation_step(self, batch: Dict[str, Any]) -> Dict[str, Any]:
        """
        Performs a single validation step (no grad update).
        Returns dictionary of outputs (e.g., {'logits': ..., 'labels': ...})
        """
        pass

    @abstractmethod
    def save(self, path: str):
        pass

    @abstractmethod
    def load(self, path: str):
        pass

    @abstractmethod
    def get_state_dict(self):
        pass

    @abstractmethod
    def get_optimizer_state_dict(self):
        pass

