# -*- coding: utf-8 -*-
"""base_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sjI_7Vgh4Gmr40chNR2_srtD4-jyRXAl
"""

from abc import ABC, abstractmethod
from typing import Dict, Any
import torch

class ModelAdapter(ABC):
    """
    This is an abstract base class that defines a common interface
    for any VQA model used in the system.
    """

    @abstractmethod
    def train_step(self, batch: Dict[str, Any]) -> Dict[str, float]:
        """
        Performs one training step on a batch of data.

        - Runs forward pass
        - Computes loss
        - Performs backpropagation
        - Updates model parameters

        Returns:
            A dictionary containing training metrics
            Example: {'loss': 2.3}
        """
        pass

    @abstractmethod
    def validation_step(self, batch: Dict[str, Any]) -> Dict[str, Any]:
        """
        Performs one validation step (no parameter updates).

        - Runs forward pass
        - Computes loss
        - Does NOT call backward()

        Returns:
            A dictionary containing outputs such as:
            - logits
            - labels
            - validation loss
        """
        pass

    @abstractmethod
    def save(self, path: str):
        """
        Saves model weights to a file.
        """
        pass

    @abstractmethod
    def load(self, path: str):
        """
        Loads model weights from a file.
        """
        pass

    @abstractmethod
    def get_state_dict(self):
        """
        Returns the model's state dictionary.
        Used for checkpointing.
        """
        pass

    @abstractmethod
    def get_optimizer_state_dict(self):
        """
        Returns the optimizer state dictionary.
        Needed to resume training from a checkpoint.
        """
        pass


