# -*- coding: utf-8 -*-
"""ViLT_vqa_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xBEaI_0iH9nbEW_mfAE3RmhNE7s37Tm_
"""

from typing import Dict
from transformers import ViltForQuestionAnswering

from typing import Dict, Tuple
from transformers import ViltConfig, ViltForQuestionAnswering

def get_clevr_model(
    answer2id: Dict[str, int],
    checkpoint: str = "dandelin/vilt-b32-mlm-itm",
) -> ViltForQuestionAnswering:
    """
    Load ViLT and resize the VQA classifier to len(answer2id).
    Returns a model ready for training with batches that include `labels`.
    """
    num_labels = len(answer2id)

    # Build config with your label space
    config = ViltConfig.from_pretrained(
        checkpoint,
        num_labels=num_labels,
        id2label={i: ans for ans, i in answer2id.items()},
        label2id=answer2id,
    )

    # Load weights; replace classifier head to match num_labels
    model = ViltForQuestionAnswering.from_pretrained(
        checkpoint,
        config=config,
        ignore_mismatched_sizes=True,
    )

    return model



